# This is a basic workflow to help you get started with Actions

name: Build Linux Release

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Use a container with GLIBC 2.17
    container: quay.io/pypa/manylinux2014_x86_64
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: init rustup
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh /dev/stdin -y
          source "$HOME/.cargo/env"
      - name: install depends
        run: |
          yum install -y gcc gcc-c++ make automake cmake
          rustup toolchain install nightly
          rustup target add wasm32-unknown-unknown --toolchain nightly
          yum install llvm-toolset-7
          scl enable llvm-toolset-7 bash
      - name: build
        run: cargo build -r
